### ISSUE TITLE
Hardware files?

### ISSUE THREAD

**Issue by salvagione** [Irdroid/LoRa-IR-Transmitter#1]
On Tindie you state “The first open source software and open source hardware LoRaWAN infrared transmitter, available. It gives you the flexibility to remotely control IR appliances , where there is no internet available at the site.”

I don’t see the schematics or the design files. Is this an open source hardware project?

**Comment by Irdroid** [comment]
Yes it is open source hardware. It uses Dragino Lora shield which is open source hardware and Irdroid Irdroino shield which is also open source hardware and it can be found at [Irdroino Repo](https://github.com/irdroid/irdroino)

**Comment by salvagione** [comment]
Thank you for the link, that's what I was looking for!
